CREATE TABLE CONTABILIZEI_CASE(
    DATA                DATE CONSTRAINT MARKET_DATE NOT NULL,
    MERCADO_ABERTO      NUMBER(30,15) CONSTRAINT OPEN_MARKET NOT NULL,
    USUARIO             NUMBER(30,15) CONSTRAINT USUARIO NOT NULL,
    NEW_USUARIO         NUMBER(30,15) CONSTRAINT NEW_USER NOT NULL,
    LEADS               NUMBER(30,15) CONSTRAINT N_LEADS NOT NULL,
    VENDAS              NUMBER(30,15) CONSTRAINT SALES NOT NULL,
    INVESTIMENTO        NUMBER(30,15) CONSTRAINT INVESTIMENT NOT NULL

);

drop TABLE CONTABILIZEI_CASE;


SELECT * FROM CONTABILIZEI_CASE;

-- ROUND    arredonda o numero em casas decimais
-- NULLLIF  tranforma valores nulos em zero fazendo com que não de erroz na query
--OVER (ORDER BY DATA) ordena dados por data antes de execultar o calculo

-- Cálculo da variação DA CONTABILIZEI

SELECT 
    DATA,
    VENDAS AS ATUAL,
    LAG(VENDAS) OVER (ORDER BY DATA) AS ANTERIOR,
    
    ROUND(
        ((VENDAS - LAG(VENDAS) OVER (ORDER BY DATA)) / 
        NULLIF(LAG(VENDAS) OVER (ORDER BY DATA), 0)) * 100, 2) 
        AS VARIACAO_PERCENTUAL
FROM CONTABILIZEI_CASE;


-- Cálculo da variação DA CONTABILIZEI MERCADO

SELECT 
    DATA,
    MERCADO_ABERTO AS ATUAL,
    LAG(MERCADO_ABERTO) OVER (ORDER BY DATA) AS ANTERIOR,
    ROUND(
        ((MERCADO_ABERTO - LAG(MERCADO_ABERTO) OVER (ORDER BY DATA)) /
        NULLIF(LAG(MERCADO_ABERTO) OVER (ORDER BY DATA) , 0)) * 100, 2) 
        AS VARIAÇÃO_MERCADO
FROM CONTABILIZEI_CASE;
        
        
--funil de vendas

--taxa de converção usuario para lead

SELECT 
        DATA,
        LEADS,USUARIO,
        
        ROUND((VENDA/LEADS)*100,2)
        AS TAXA_USUARIO_PARA_LEAD
FROM CONTABILIZEI_CASE
ORDER BY DATA;

--taxa de converção lead para venda
SELECT 
        DATA,
        LEADS,VENDAS,
        
        ROUND((VENDAS/LEADS)*100,2)
        AS TAXA_LEAD_PARA_VENDAS
FROM CONTABILIZEI_CASE
ORDER BY DATA;

--VALOR DO CAC(custo de aquisição por cliente)

SELECT 
        DATA,
        INVESTIMENTO,VENDAS,
        
        ROUND(INVESTIMENTO/VENDAS,2)
        AS INVESTIMENTO_P_CLIENTE
FROM CONTABILIZEI_CASE
ORDER BY DATA;

--EFCIENCIA DO VALOR INVESTIDO EM MERKETING

SELECT 
        DATA,
        INVESTIMENTO,LEADS,
        
        ROUND(INVESTIMENTO/LEADS,2)
        AS INVESTIMENTO_P_LEAD
FROM CONTABILIZEI_CASE
ORDER BY DATA;


SELECT 
    DATA,
    VENDAS,
    MERCADO_ABERTO,
    INVESTIMENTO,
    -- Calcula a meta de 6% do mercado
    (MERCADO_ABERTO * 0.06) AS META_DE_VENDAS,
    -- Calcula o investimento necessário: (Meta * CAC)
    ROUND((MERCADO_ABERTO * 0.06) * (INVESTIMENTO / VENDAS), 2) AS VALOR_INVESTIMENTO
FROM CONTABILIZEI_CASE
WHERE DATA = '04/01/22';

